### ISSUE TITLE
Getting TypeError on Windows Chrome

### ISSUE THREAD

**Issue by tomharvey** [rehanvdm/serverless-website-analytics-client#12] opened 2023-09-08 19:37 UTC
Pushed out my use of SWA (great) now sentry is throwing a lot of errors.

Seems to be raised when I do the fairly straight forward `swaClient.v1.analyticsPageChange("/");` (and on paths that are not just "/")

It seems to **all** be on Chrome browser on Windows >= 10

```
TypeError: Illegal invocation
    at c (https://example.com/static/js/main.e0024c89.js:2:834156)
    at Object.e.analyticsPageChange (https://example.com/static/js/main.e0024c89.js:2:835129)
    at qn (https://example.com/static/js/main.e0024c89.js:2:858212)
    at _a (https://example.com/static/js/main.e0024c89.js:2:488661)
    at _s (https://example.com/static/js/main.e0024c89.js:2:545774)
    at wc (https://example.com/static/js/main.e0024c89.js:2:534880)
    at gc (https://example.com/static/js/main.e0024c89.js:2:534808)
    at mc (https://example.com/static/js/main.e0024c89.js:2:534671)
    at ac (https://example.com/static/js/main.e0024c89.js:2:531451)
    at ic (https://example.com/static/js/main.e0024c89.js:2:530002)
    at S (https://example.com/static/js/main.e0024c89.js:2:619013)
    at C (https://example.com/static/js/main.e0024c89.js:2:619547)
    at T.<computed> (https://example.com/static/js/main.e0024c89.js:2:291851)
    at j (https://example.com/static/js/main.e0024c89.js:2:291620)
    at MessagePort.R (https://example.com/static/js/main.e0024c89.js:2:291679)
```

Not sure if you've seen this behaviour?

**Comment by rehanvdm** [comment] 2023-09-09 05:02
I can't say that I have. So just to clarify, that error is from Sentry? 

Are you shipping Sourcemaps to Sentry at deploy time? We won't be able to narrow it down without good stack traces. For what it is worth, this package does have sourcemaps. 
![image](https://github.com/rehanvdm/serverless-website-analytics-client/assets/22810856/2463ea09-d8f9-433a-8cdb-a2e09ce84de3)

**Comment by rehanvdm** [comment] 2023-09-09 05:17
I thought it might be Chrome because they have new Privacy settings for ads now. bit it does not look like it is the case.

Can you confirm if it is still sending network requests? 

Here is one of my sites: https://www.rehanvdm.com/ and in the console I also see an error, it might or might not be the same because that site is old Nuxt2 and glued together. 

On this site I also have it enabled https://blog.cloudglance.dev/ and there are no errors, everything just works. Same for the demo page: https://demo.serverless-website-analytics.com

First step will be reproducing what is causing it. Can you run your site locally, you should be able to have sourcemaps then and better stack traces?

**Comment by rehanvdm** [comment] 2024-04-10 18:03
Closing this for now, let me know if you ever solved it or if it is still a problem

**Closed as completed by rehanvdm** 2024-04-10 18:03 UTC
